services:
  - type: worker
    name: gs-job-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tracker.py
    plan: free
    healthCheckPath: /
    autoDeploy: true 